### ISSUE TITLE
After update Local notifications.schedule not a function

### ISSUE THREAD

**Issue by devyaz** [EddyVerbruggen/nativescript-local-notifications#129]
Here's my stack trace
 ```An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method call failed
TypeError: LocalNotifications.schedule is not a function
File: "file:///data/data/com.malachat.aio/files/app/connection.js, line: 84, column: 22
StackTrace: 
	Frame: function:'', file:'file:///data/data/com.malachat.aio/files/app/connection.js', line: 84, column: 23
	Frame: function:'listener', file:'file:///data/data/com.malachat.aio/files/app/tns_modules/nativescript-socket.io/socketio.js', line: 84, column: 22


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.access$2300(Runtime.java:34)
	at com.tns.Runtime$3.run(Runtime.java:1136)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
Before everything worked without a problem now on ver:3.1.0 below my code
```
LocalNotifications.schedule([{
       id: id+1,
        title: 'MalaChat',
        body: msg,
        ticker: 'New Message ',
        color:  '',
        badge: 1,
        groupedMessages:[msg], //android only
        groupSummary:"Summary of the grouped messages above", //android only
        ongoing: false, // makes the notification ongoing (Android only)
        icon: 'res://heart',
        image: "https://cdn-images-1.medium.com/max/1200/1*c3cQvYJrVezv_Az0CoDcbA.jpeg",
        thumbnail: true,
       // interval: 'minute',
        channel: 'My Channel', // default: 'Channel'
        sound: "customsound-ios.wav", // falls back to the default sound on Android
        at: new Date(new Date().getTime()) // 10 miliseconds from now
     }]).then(
         function() {
           console.log("Notification scheduled on main Thread!");
         },
         function(error) {
           console.log("scheduling error: " + error);
         }
     )
});
```

**Comment by EddyVerbruggen** [comment]
What did you update? The plugin or NativeScript? In either case, have you tried removing the `platforms` folder?

Please share a repo for further assistance.

**Comment by devyaz** [comment]
Hi Eddy I'll try that, I updated the plugin first,then {N} last week to v5
, during upgrade to v5 it removed the projects platform but still no luck
I'll try manually removing and re-adding
