### ISSUE TITLE
Vue demo app error entry point not found

### ISSUE THREAD

**Issue by priyankcommits** [EddyVerbruggen/nativescript-local-notifications#140]
Trying to run the latest vue demo app, running into the following error
Command `npm run demo-vue.ios`
Result
`
➜  src git:(master) ✗ npm run demo-vue.ios

> nativescript-local-notifications@3.1.2 demo-vue.ios /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/src
> npm run build && cd ../demo-vue && tns run ios --bundle --syncAllFiles

> nativescript-local-notifications@3.1.2 build /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/src
> npm i && tsc --skipLibCheck

audited 74 packages in 1.88s
found 0 vulnerabilities

Searching for devices...
Executing before-watchPatterns hook from /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/hooks/before-watch/nativescript-dev-webpack.js
Running webpack for iOS...
/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: The entry module main specified in /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/app/package.json doesn't exist!
    at Object.exports.getEntryModule (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/nativescript-dev-webpack/index.js:36:15)
    at module.exports.env (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/webpack.config.js:56:35)
    at handleFunction (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/prepareOptions.js:21:13)
    at prepareOptions (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/convert-argv.js:118:14)
    at /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/yargs/yargs.js:567:18)
    at /Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/priyankpulumati/Desktop/learn_vue/nativescript-local-notifications/demo-vue/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
Executing webpack failed with exit code 1.
Cannot read property 'kill' of undefined
`

**Comment by EddyVerbruggen** [comment]
Thanks for reporting that, I'll take a look!

**Comment by EddyVerbruggen** [comment]
OK, please try again, following the instructions in the readme.
