### ISSUE TITLE
After installing - (Other plugin crush the app)

### ISSUE THREAD

**Issue by dudipsh** [EddyVerbruggen/nativescript-local-notifications#170]
When I delete the plugin bring back to normal.
In this case The other plugin is mine

https://github.com/dudipsh/nativescript-ngx-date-range

Any idea what makes this issue?

The error:

```text
dudis-MacBook-Pro:timetablePlus dudipartush$ tns run android --bundle
Searching for devices...
Preparing project...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 749d7ec1cb4b3937422d
Version: webpack 4.27.1
Time: 18814ms
Built at: 10/18/2019 8:49:52 PM
                        Asset       Size   Chunks             Chunk Names
                         0.js    264 KiB        0  [emitted]  
                         1.js    239 KiB        1  [emitted]  
                        10.js     48 KiB       10  [emitted]  
                        11.js   14.9 KiB       11  [emitted]  
                        12.js   41.6 KiB       12  [emitted]  
                         2.js    312 KiB        2  [emitted]  
                         3.js    129 KiB        3  [emitted]  
                         4.js     62 KiB        4  [emitted]  
                         5.js     36 KiB        5  [emitted]  
                         6.js     27 KiB        6  [emitted]  
                         7.js   82.2 KiB        7  [emitted]  
                         8.js   16.5 KiB        8  [emitted]  
                         9.js   16.8 KiB        9  [emitted]  
    assets/icons/png/menu.png  176 bytes           [emitted]  
assets/images/no-internet.png   17.5 KiB           [emitted]  
   assets/images/selected.png  963 bytes           [emitted]  
assets/images/userProfile.jpg   11.8 KiB           [emitted]  
     assets/logo/new_logo.png     14 KiB           [emitted]  
                    bundle.js    894 KiB   bundle  [emitted]  bundle
        fonts/FontAwesome.ttf    162 KiB           [emitted]  
        fonts/Rubik-Black.ttf    135 KiB           [emitted]  
         fonts/Rubik-Bold.ttf    132 KiB           [emitted]  
        fonts/Rubik-Light.ttf    127 KiB           [emitted]  
       fonts/Rubik-Medium.ttf    133 KiB           [emitted]  
      fonts/Rubik-Regular.ttf    130 KiB           [emitted]  
      fonts/fa-brands-400.ttf    126 KiB           [emitted]  
       fonts/fa-light-300.ttf    391 KiB           [emitted]  
     fonts/fa-regular-400.ttf    361 KiB           [emitted]  
       fonts/fa-solid-900.ttf    306 KiB           [emitted]  
                 i18n/en.json   7.47 KiB           [emitted]  
                 i18n/he.json   8.95 KiB           [emitted]  
                 package.json  112 bytes           [emitted]  
                   runtime.js     73 KiB  runtime  [emitted]  runtime
          tns-java-classes.js    0 bytes           [emitted]  
                    vendor.js   20.1 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace object 160 bytes {bundle} [built]
[../node_modules/css-loader/dist/cjs.js?!./animate.css] ../node_modules/css-loader/dist/cjs.js??ref--7-1!./animate.css 87.3 KiB {bundle} [built]
[./app.scss] 25.2 KiB {bundle} [built]
[./app/app-routing.module.ts] 1.87 KiB {bundle} [built]
[./app/app.component.html] 6.03 KiB {bundle} [built]
[./app/app.component.scss] 19 bytes {bundle} [built]
[./app/app.component.ts] 2.03 KiB {bundle} [built]
[./app/app.module.ts] 4.96 KiB {bundle} [built]
[./app/shared/factory/interceptor.ts] 3.04 KiB {bundle} [built]
[./app/shared/helpers/common.ts] 9.34 KiB {bundle} [built]
[./app/shared/helpers/process.ts] 1.71 KiB {bundle} [built]
[./app/shared/services/data.service.ts] 12.2 KiB {bundle} [built]
[./app/shared/services/mobile.service.ts] 2.47 KiB {bundle} [built]
[./app/shared/services/user.service.ts] 5.56 KiB {bundle} [built]
[./main.ts] 2.46 KiB {bundle} [built]
    + 978 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred runtime.js on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application il.co.timetable.timeTablePlus on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:663)
System.err:     at com.tns.Runtime.run(Runtime.java:655)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:22)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more
Chokidar raised event change for /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/App_Resources/Android/app.gradle.
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/App_Resources/Android/app.gradle
         Applying settings from /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/App_Resources/Android/settings.json
         + using andorid X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/@nativescript-rtl/ui/platforms/android/nativescript_gridlayout.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/@nativescript-rtl/ui/platforms/android/ui.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/@nativescript-rtl/ui/platforms/android/nativescript_grid_layout.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-app-sync/platforms/android/tnsappsync.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-background-http/platforms/android/nativescript_background_http.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-geolocation/platforms/android/nativescript_geolocation.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-imagecropper/platforms/android/nativescript_imagecropper.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-imagepicker/platforms/android/nativescript_imagepicker.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-local-notifications/platforms/android/app-release.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-menu/platforms/android/nativescript_menu.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-ngx-date-range/platforms/android/app-release.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-ngx-date-range/platforms/android/nativescript_ngx_date_range.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-phone/platforms/android/nativescript_phone.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-ui-listview/platforms/android/TNSListView-release.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-ui-sidedrawer/platforms/android/TNSSideDrawer-release.aar
         + adding jar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-zip/platforms/android/zip4j_1.3.2.jar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
         + adding aar plugin dependency: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
Project successfully built.
The build result is located at: /Users/dudipartush/Documents/Dev/Projects/newTimeTable/timetablePlus/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application il.co.timetable.timeTablePlus on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err: File: "file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'../node_modules/nativescript-ngx-date-range/ngx-date-range.js', file:'file:///node_modules/nativescript-ngx-date-range/ngx-date-range.js:8:0
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/date-picker-modal/date-picker-modal.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1348, column: 85
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.component.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1466, column: 104
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/dropdown/dropdown.module.tns.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 1625, column: 77
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/shared/components/shared-components/shared-components.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2056, column: 127
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'./app/app.module.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 488, column: 124
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4836, column: 73
System.err:     Frame: function:'./main.ts', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 4919, column: 30
System.err:     Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err:     Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err:     Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err:     Frame: function:'', file:'file:///data/data/il.co.timetable.timeTablePlus/files/app/bundle.js', line: 2, column: 57
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'daterange' of undefined
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:663)
System.err:     at com.tns.Runtime.run(Runtime.java:655)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:22)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
System.err:     ... 8 more

```

**Comment by ihazar** [comment]
You didn't share your nativescript version. I'm facing the same problem. Please note that Plugin version 4.0.0 should be used with NativeScript 6+. If you have an older tns --version, please use an older plugin version.

**Comment by dudipsh** [comment]
@ihazar 
I use NativeScript 6.0.3
I think there's a chance it's related to the fact that this plugin uses AndroidX
